"use client";

import { useState } from "react";
import Link from "next/link";
import { serviceCategories, type ServiceCategory } from "@/data/service-categories";

export function ServiceExplorer() {
  const [active, setActive] = useState<ServiceCategory | null>(null);
  return <section className="service-explorer" id="layanan"><div className="section-shell"><div className="service-heading"><div><p className="section-kicker">Jelajahi berdasarkan kebutuhan</p><h2>Apa yang ingin <em>kamu urus?</em></h2></div><p>Temukan layanan administrasi<br />dengan cara yang lebih mudah.</p></div><div className="service-grid">{serviceCategories.map((service) => <button className={`service-card ${active?.name === service.name ? "is-active" : ""}`} key={service.name} type="button" onClick={() => setActive(active?.name === service.name ? null : service)}><span className={`service-icon ${service.accent}`}>{service.icon}</span><strong>{service.name}</strong><span className="service-description">{service.description}</span><span className={`service-badge ${service.accent}`}>{service.count} layanan</span><span className="service-corner">↗</span></button>)}</div><div className="service-all-action"><Link href="/layanan">Lihat Semua Layanan <span>→</span></Link></div><div className="service-footer"><span>{active ? <><b>{active.name}</b> — pilih urusan yang ingin kamu ambil.</> : "Pilih kategori untuk melihat daftar urusannya."}</span><button type="button" onClick={() => setActive(serviceCategories[0])}>Lihat daftar urusan <b>→</b></button></div>{active && <div className="service-selection"><div className="service-selection-heading"><div><span className={`service-icon ${active.accent}`}>{active.icon}</span><div><p className="preview-label">Urusan dalam kategori</p><h3>{active.name}</h3></div></div><button type="button" onClick={() => setActive(null)} aria-label="Tutup daftar">×</button></div><div className="service-task-grid">{active.items.map((item) => <button className="service-task" type="button" key={item.title}><span className={`task-icon ${active.accent}`}>{item.icon}</span><span><strong>{item.title}</strong><small>{item.description}</small><em>◷ {item.duration}</em></span><b>→</b></button>)}</div><a className="service-guide-link" href="/cara-kerja">Lihat cara kerja layanan <span>→</span></a></div>}</div></section>;
}