"use client";

import { useState } from "react";

const steps = [["Ceritakan peristiwanya", "Pilih situasi yang paling dekat dengan keadaanmu saat ini.", "Kamu tidak perlu tahu nama instansinya dulu."], ["Kami susun peta urusan", "SatuUrusan menghubungkan kebutuhan yang biasanya tersebar.", "Hal penting diurutkan berdasarkan konteks dan prioritas."], ["Kamu ikuti langkahnya", "Tandai progres dan siapkan hal yang diperlukan di setiap tahap.", "Checklist sederhana membuatmu tahu apa yang sudah selesai."], ["Terhubung ke kanal resmi", "Setiap layanan tetap dilakukan di situs atau kantor resmi.", "Kami membantu menemukan pintu yang tepat, bukan menggantikannya."]];
const guides = [["✦", "Pahami SatuUrusan", "Kenali cara kami membantu merapikan urusanmu."], ["▤", "Lihat contoh alur", "Ikuti contoh dari satu peristiwa sampai selesai."], ["?", "Tanya SatuAI", "Dapatkan bantuan untuk menentukan langkah pertama."]];
const questions = [["Bagaimana cara memulai proses administrasi?", "Pilih satu peristiwa hidup yang sedang kamu alami. SatuUrusan akan membantu menghubungkan kebutuhan yang muncul dan menyusunnya menjadi langkah."], ["Apakah SatuUrusan memproses dokumen langsung?", "Tidak. SatuUrusan hanya membantu memahami proses dan mengarahkanmu ke kanal resmi pemerintah."], ["Apakah informasi yang diberikan sudah resmi?", "Kami menampilkan sumber, waktu verifikasi, dan tautan ke kanal resmi agar kamu bisa memeriksanya sebelum melanjutkan."], ["Apa yang terjadi setelah saya memilih satu peristiwa?", "Kamu akan melihat peta urusan, persiapan yang dibutuhkan, dan tindakan berikutnya yang paling relevan."]];

export function WorkGuide() {
  const [activeStep, setActiveStep] = useState(0);
  const [query, setQuery] = useState("");
  const [openQuestion, setOpenQuestion] = useState<number | null>(null);
  const filteredQuestions = questions.filter(([question, answer]) => `${question} ${answer}`.toLowerCase().includes(query.toLowerCase()));
  return <main className="work-page">
    <section className="work-hero"><div className="work-hero-content"><p className="section-kicker">Panduan SatuUrusan</p><h1>Ada yang ingin<br /><em>kamu pahami?</em></h1><p>Temukan jawaban, panduan, dan cara kerja yang kamu butuhkan.</p><label className="work-search"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Cari informasi tentang cara kerja..." /></label></div></section>
    <section className="guide-shortcuts"><div className="section-shell"><div className="guide-grid">{guides.map(([icon, title, description]) => <button type="button" className="guide-card" key={title} onClick={() => document.getElementById(title === "Lihat contoh alur" ? "alur" : "faq")?.scrollIntoView({ behavior: "smooth" })}><span>{icon}</span><strong>{title}</strong><small>{description}</small></button>)}</div></div></section>
    <section className="work-flow" id="alur"><div className="section-shell"><div className="work-section-heading"><div><p className="section-kicker">Alur sederhana</p><h2>Begini cara <em>kerjanya.</em></h2></div><p>Empat langkah untuk membuat urusan<br />terasa lebih mudah diikuti.</p></div><div className="step-tabs">{steps.map((step, index) => <button type="button" className={activeStep === index ? "active" : ""} key={step[0]} onClick={() => setActiveStep(index)}><span>0{index + 1}</span>{step[0]}</button>)}</div><div className="step-stage"><div className="step-stage-number">0{activeStep + 1}</div><div><p className="section-kicker">Langkah {activeStep + 1} dari 4</p><h2>{steps[activeStep][0]}</h2><p>{steps[activeStep][1]}</p><span className="stage-tip">✦ {steps[activeStep][2]}</span></div><div className="stage-progress"><span style={{ width: `${((activeStep + 1) / steps.length) * 100}%` }} /></div></div></div></section>
    <section className="work-faq" id="faq"><div className="section-shell"><div className="work-section-heading"><div><p className="section-kicker">Pertanyaan umum</p><h2>Masih ingin <em>tahu lebih?</em></h2></div><p>Jawaban singkat tentang cara kerja<br />dan batasan SatuUrusan.</p></div><div className="work-faq-list">{filteredQuestions.map(([question, answer], index) => <div className={`work-faq-item ${openQuestion === index ? "open" : ""}`} key={question}><button type="button" onClick={() => setOpenQuestion(openQuestion === index ? null : index)}><span>{question}</span><b>{openQuestion === index ? "−" : "+"}</b></button>{openQuestion === index && <p>{answer}</p>}</div>)}{filteredQuestions.length === 0 && <p className="empty-state">Belum menemukan jawaban. Coba kata kunci lain.</p>}</div></div></section>
  </main>;
}
